import React from 'react';
import styled from 'styled-components';

const LoadingContainer = styled.div`



@keyframes ldio-gx5diy917eb-1 {
  0% { top: 43.466px; height: 124.06799999999998px }
  50% { top: 61.19px; height: 88.61999999999999px }
  100% { top: 61.19px; height: 88.61999999999999px }
}
@keyframes ldio-gx5diy917eb-2 {
  0% { top: 47.897000000000006px; height: 115.20599999999997px }
  50% { top: 61.19px; height: 88.61999999999999px }
  100% { top: 61.19px; height: 88.61999999999999px }
}
@keyframes ldio-gx5diy917eb-3 {
  0% { top: 52.327999999999996px; height: 106.344px }
  50% { top: 61.19px; height: 88.61999999999999px }
  100% { top: 61.19px; height: 88.61999999999999px }
}
.ldio-gx5diy917eb div { position: absolute; width: 27.43px }.ldio-gx5diy917eb div:nth-child(1) {
  left: 39.035px;
  background: #ea33bc;
  animation: ldio-gx5diy917eb-1 1.0416666666666665s cubic-bezier(0,0.5,0.5,1) infinite;
  animation-delay: -0.20833333333333331s
}
.ldio-gx5diy917eb div:nth-child(2) {
  left: 91.785px;
  background: #ea33bc;
  animation: ldio-gx5diy917eb-2 1.0416666666666665s cubic-bezier(0,0.5,0.5,1) infinite;
  animation-delay: -0.10416666666666666s
}
.ldio-gx5diy917eb div:nth-child(3) {
  left: 144.535px;
  background: #ea33bc;
  animation: ldio-gx5diy917eb-3 1.0416666666666665s cubic-bezier(0,0.5,0.5,1) infinite;
  animation-delay: undefineds
}

.loadingio-spinner-pulse-52llprnz1zf {
  width: 211px;
  height: 211px;
  display: inline-block;
  overflow: hidden;

}
.ldio-gx5diy917eb {
  width: 100%;
  height: 100%;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-gx5diy917eb div { box-sizing: content-box; }
/* generated by https://loading.io/ */
`
export default function Loading() {
    return (
        <LoadingContainer>
            <div class="loadingio-spinner-pulse-52llprnz1zf"><div class="ldio-gx5diy917eb">
                <div></div><div></div><div></div>
            </div></div>
        </LoadingContainer>
    )
}



